### ISSUE TITLE
send notification mail to user when a double opt-in was completed

### ISSUE THREAD

**Issue by medarob** [linawolf/form_double_opt_in#12]
Right now you don't know when a double opt-in was successfully completed other than checking the TYPO3 BE.

So, if someone would register for a newsletter you would have to check the TYPO3 BE for new entries.

It would be great to have an option which sends automatically an email to an in-house user/employee whenever a double opt-in was successfully completed.

There is an open pull request which already seems to have this feature integrated. Maybe it's possible to merge this into the extension?

**Comment by linawolf** [comment]
@danielkestler I believe this ticket can be closed now
