### ISSUE TITLE
Publish to TER

### ISSUE THREAD

**Issue by linawolf** [linawolf/form_double_opt_in#25]
Publish the newsest versions to TER please. Currently the extension only seems to be compatible up to TYPO3 v9: https://extensions.typo3.org/extension/form_doubleoptin If you don't want to do that manually each you can introduce a GitHub Action for that

**Comment by danielkestler** [comment]
Does TER still have relevance for anyone? If we can do it automatically, then maybe ...

**Comment by linawolf** [comment]
In my eyes the worth of TER is more that you can search for extensions, use the filtering, have handy links to the docs, source, composer name etc. See https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/HowTo/PublishExtension/PublishToTER/Index.html#how-to-publish-an-extension

**Comment by helsner** [comment]
Stepping by and commenting to support this.
I check TER first before google..
TER gives me extensions.. google often delivers blog entries, also about the same functionalities etc. and other stuff i dont need 
When i want an extension, i search at the "extension market" thus TER

**Comment by linawolf** [comment]
Currently the automatic registration of extensions does not work for the TER. Will tackle this as soon as it is working again

**Comment by xerc** [comment]
fyi/ the link in the first comment and the following one lead to here
https://extensions.typo3.org/package/linawolf/form_double_opt_in

**Comment by linawolf** [comment]
Thanks a lot, so this seems to be resolved then

**Comment by linawolf** [comment]
What you mean? The extension is now available in the TER it seems?

**Comment by linawolf** [comment]
That would be an issue for the typo3 website team
