### ISSUE TITLE
Error after sending form

### ISSUE THREAD

**Issue by nannione** [linawolf/form_double_opt_in#26]
Hello,
 
with TYPO3 and form both version 10.4.36 and form_double_opt_in 3.0.0 i get following error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function TYPO3\CMS\Form\Domain\Finishers\EmailFinisher::getRecipients(), 1 passed in /usr/../typo3conf/ext/form_double_opt_in/Classes/Domain/Finishers/DoubleOptInFormFinisher.php on line 162 and at least 2 expected | ArgumentCountError thrown in file /usr/../typo3/sysext/form/Classes/Domain/Finishers/EmailFinisher.php in line 335. Requested URL: https:/xxxxxx.de/testform?tx_form_formframework%%5Baction%%5D=perform&tx_form_formframework%%5Bcontroller%%5D=FormFrontend&cHash=7c922fc6ac81df12c8d566a25661a865

**Comment by medarob** [comment]
Mh, I just ran into the same problem.
![grafik](https://user-images.githubusercontent.com/33951787/229786275-c65d3250-b077-4110-9692-cd7da97154dd.png)

I updated from v2.1.1 to 3.0 and changed the custom constants settings. 🤔

**Comment by linawolf** [comment]
AS TYPO3 v10.4 is not supported anymore I will not work on this topic anymore. Sorry about this
