### ISSUE TITLE
404 caused by ampersand being escaped in confirmation link

### ISSUE THREAD

**Issue by y-oshua** [linawolf/form_double_opt_in#34]
Had to add f:format.raw tags around the uri builder because fluid automatically escapes inline rendered variables, could also just add `{escaping off}` to beginning of email templates.

Here was my solution:
`<f:format.raw>{f:uri.action(pageUid: validationPid, extensionName: 'formdoubleoptin', pluginName: 'doubleoptin', controller: 'DoubleOptIn', action: 'validation', absolute: 1, arguments: {hash: optIn.validationHash})}</f:format.raw>`

**Comment by linawolf** [comment]
PR is merged
